name: Generate summary cards

on:
  schedule:
    - cron: "0 0 * * *" # Executa todos os dias às 00:00 UTC
  workflow_dispatch: # Permite execução manual do workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Generate summary cards
        run: |
          npx github-profile-summary-cards@latest
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update profile summary cards"
          git push
